f1=open("students.txt","w")
f1.write("Name: Priyanshu\n")
f1.close()
f1=open("students.txt","r")
data=f1.read()
print(f1.tell())
print(f1.seek(2))
print(f1.tell())
print(f1.readline()) 
f1.close()